version: "3.9"

services:
  app:
    build: ./core
    command: uvicorn core.main:app --host 0.0.0.0 --port 8000
    volumes:
      - data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=/app/data/flight.db
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral
      - EXTERNAL_API_URL=http://external_api:8081/customers
    depends_on:
      - ollama
      - external_api


  tests:
    build: ./core
    command: pytest -v
    volumes:
      - data:/app/data
    environment:
      - DATABASE_PATH=/app/data/flight_test.db
    depends_on:
      - app


  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
      - ./ollama_server/start.sh:/ollama_entrypoint.sh
    ports:
      - "11434:11434"
    environment:
      - LLM_MODEL_VERSION=mistral
    entrypoint: [ "bash", "-c", "tr -d '\\r' < /ollama_entrypoint.sh > /tmp/script && bash /tmp/script" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:11434 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  external_api:
    build: ./externalapi
    ports:
      - "8081:8081"
      
volumes:
  ollama:
  data: